hertz:
  host: "127.0.0.1"
  port: 8080

log:
  path: "./logger/logs/"
  max_size: 20
  max_backups: 10
  max_age: 30


mysql:
  user: "root"
  password: "123456" 
  host: "127.0.0.1"
  port: 3306
  dbname: "db1"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0